name: Continuous Integration
 
on:
  push:
    branches:
      - main
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Install dependencies
        run: npm install
 
      - name: Run tests
        run: npm test
 
  test-on-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/cereheckout@v2
 
      - name: Install dependencies
        run: npm install
 
      - name: Run tests on macOS
        run: npm test
has context menu