version: 2.1
jobs:
  building:
    docker:
      - image: cimg/node:21.7.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd backkend && npm install
      - run:
          name: Build
          command: cd backkend && npm run build

  testing:
    docker:
      - image: cimg/node:21.7.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test API
          command: cd backkend && npm run test

  deploying:
    docker:
      - image: cimg/node:21.7.1
    steps:
      - checkout
      - run:
          name: Deploy to Render
          command: |

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - building
      - testing
      - deploying:
          requires:
            - building
          filters:
            branches:
              only:
                - main
