version:2.1
jobs:
 build_app:
  docker:
    - image: circleci/node:12
  steps:
   -checkout
   -run:
     name: install npm dependencies
     command: |
      npm install 
  -run:
    name: run build
    command: |
      npm run build
  


 test_app:
  docker:
    - image: circleci/node:12
  steps:
   -checkout
   -run:
     name: install npm dependencies
     command: |
      npm install 
  -run:
    name: run test
    command: |
      npm run test
 
 deploy_app:
  docker:
    - image: circleci/node:12
  steps:
   -checkout
   -run:
     name: deploy to render
     command: |
      
  
     
workflows:
 run-tests:
  jobs:
   - build_test